server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location = /api/v1/index { proxy_pass http://adapter-btc:8080/api/v1/index; }
  location /api/v1/       { proxy_pass http://adapter-btc:8080/api/v1/; }

  location /poolapi/btc/  { proxy_pass http://adapter-btc:8080/api/v1/; }
  location /poolapi/bch/  { proxy_pass http://adapter-bch:8080/api/v1/; }
  location /poolapi/bc2/  { proxy_pass http://adapter-bc2:8080/api/v1/; }
  location /poolapi/bch2/ { proxy_pass http://adapter-bch2:8080/api/v1/; }
  location /poolapi/btcs/ { proxy_pass http://adapter-btcs:8080/api/v1/; }
  location /poolapi/rvn/  { proxy_pass http://adapter-rvn:8080/api/v1/; }
  location /poolapi/lcc/  { proxy_pass http://adapter-lcc:8080/api/v1/; }
  location /poolapi/wjk/  { proxy_pass http://adapter-wjk:8080/api/v1/; }
  location /poolapi/grs/  { proxy_pass http://adapter-grs:8080/api/v1/; }
  location /poolapi/xec/  { proxy_pass http://adapter-xec:8080/api/v1/; }
  location /poolapi/dgb/  { proxy_pass http://adapter-dgb:8080/api/v1/; }
  location /poolapi/dgco/ { proxy_pass http://adapter-dgco:8080/api/v1/; }
  location /poolapi/bgco/ { proxy_pass http://adapter-dgco:8080/api/v1/; }
  location /poolapi/smly/ { proxy_pass http://adapter-smly:8080/api/v1/; }

  location / {
    try_files $uri $uri/ /index.html;
    add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
  }
}
